### ISSUE TITLE
Accidental self-SQL-Injection

### ISSUE THREAD

**Issue by JamesPaulKnox** [JamesPaulKnox/mortgage-database#4]
Without really looking at it, I have a hypothesis. If all these files imported correctly, and Q1 1999 didn't, and SQL is giving a syntax error, I bet that somewhere in the Q1 1999 file is going to be a double quote or something along those lines. The error is coming from SQL, not python, so some value in the file must be messing up the SQL command.

I'm going to modify the code so that it displays every SQL command it sends. When it does throw the error, I can see exactly what it was trying to execute.

```
[james@decimator scripts]$ python 2_populate_raw_tables.py 
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42000.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42009.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42007.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42003.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q22010.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32013.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42011.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42004.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32001.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32016.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q12004.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q22017.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42016.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q22003.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q12000.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q12015.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q12003.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q12001.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42008.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32006.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q22013.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42001.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32011.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32008.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32009.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32003.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q22007.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q22004.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q42005.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q32017.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q12017.txt
/run/media/james/MediaB/projects/agency_loan_level/import/freddie_origination/historical_data1_Q11999.txt
Traceback (most recent call last):
  File "2_populate_raw_tables.py", line 34, in <module>
    populate("raw_freddie_origination", 27)
  File "2_populate_raw_tables.py", line 18, in populate
    c.execute("INSERT INTO " + table + " VALUES (" + data + ");")
sqlite3.OperationalError: near "S": syntax error
```

**Comment by JamesPaulKnox** [comment]
There were many successful SQL commands executed before this. I've included numerous working ones to demonstrate it's specific to one line in the import file, making a bad SQL command.

```
INSERT INTO raw_freddie_origination VALUES ('698','199903','N','202902','47644','000','1','P','80','37','220000','80','6.875','R','N','FRM','MI','SF','48000','F199Q1000229','N','360','02','GMAC MORTGAGE CORPOR','GMACMTGECORP','
','');
INSERT INTO raw_freddie_origination VALUES ('748','199904','N','202903','47644','000','1','P','37','24','84000','37','7.125','R','N','FRM','MI','SF','48000','F199Q1000230','C','360','02','GMAC MORTGAGE CORPOR','GMACMTGECORP','
','');
INSERT INTO raw_freddie_origination VALUES ('748','199912','N','202903','11300','000','1','P','59','15','100000','59','8.25','R','N','FRM','IN','SF','46000','F199Q1000231','P','352','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('755','199903','N','202902','41940','999','1','P','70','14','220000','70','7','T','N','FRM','CA','PU','95000','F199Q1000232','N','360','02','NAMCO ASSET MANAGEME','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('647','199903','N','202902','42044','25','1','P','90','24','158000','90','6.875','T','N','FRM','CA','SF','92800','F199Q1000233','N','360','02','NAMCO ASSET MANAGEME','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('731','199903','Y','202902','41884','999','1','P','32','42','200000','32','7.125','R','N','FRM','CA','SF','94900','F199Q1000234','P','360','01','PNC MORTGAGE CORPORA','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('626','199904','N','202903','42644','000','1','P','75','32','197000','75','6.75','T','N','FRM','WA','SF','98000','F199Q1000235','C','360','01','G N MORTGAGE CORPORA','BAMORTGAGE,LLC','
','');
INSERT INTO raw_freddie_origination VALUES ('684','199903','N','202902','42644','000','1','P','79','50','150000','79','6.625','T','N','FRM','WA','SF','98100','F199Q1000236','C','360','01','G N MORTGAGE CORPORA','BAMORTGAGE,LLC','
','');
INSERT INTO raw_freddie_origination VALUES ('687','199905','N','202904','16974','000','2','P','53','36','75000','53','7.25','T','N','FRM','IL','SF','60600','F199Q1000237','C','360','01','G N MORTGAGE CORPORA','BAMORTGAGE,LLC','
','');
INSERT INTO raw_freddie_origination VALUES ('694','199905','N','202904','24660','000','1','P','79','31','73000','79','7.125','T','N','FRM','NC','SF','27200','F199Q1000238','C','360','02','G N MORTGAGE CORPORA','BAMORTGAGE,LLC','
','');
INSERT INTO raw_freddie_origination VALUES ('765','199903','9','202902','36084','999','1','P','56','14','112000','56','6.75','R','N','FRM','CA','SF','94800','F199Q1000239','N','360','02','WASHINGTON MUTUAL BA','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('696','199903','9','202902','41884','999','1','P','75','43','240000','75','6.875','R','N','FRM','CA','SF','94400','F199Q1000240','N','360','01','WASHINGTON MUTUAL BA','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('591','199904','N','202903','31084','999','1','P','19','999','30000','19','7','R','N','FRM','CA','SF','91700','F199Q1000241','P','360','01','WASHINGTON MUTUAL BA','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('713','199904','9','202903','36740','999','1','I','65','19','84000','65','7.5','R','N','FRM','FL','PU','32800','F199Q1000242','P','360','01','WASHINGTON MUTUAL BA','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('717','199903','9','202902','47644','12','1','P','85','29','140000','85','6.875','R','N','FRM','MI','SF','48800','F199Q1000243','N','360','02','Other sellers','BANKOFAMERICA,NA','
','');
INSERT INTO raw_freddie_origination VALUES ('627','199905','9','202904','19804','000','1','P','71','24','188000','71','7.5','R','N','FRM','MI','CO','48100','F199Q1000244','N','360','01','Other sellers','BANKOFAMERICA,NA','
','');
INSERT INTO raw_freddie_origination VALUES ('763','199903','N','202902','40420','000','1','P','63','24','101000','63','7.25','R','N','FRM','IL','SF','61000','F199Q1000245','C','360','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('721','199903','Y','202902','','30','1','P','95','41','60000','95','7','R','','FRM','WI','SF','54600','F199Q1000246','P','360','01','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('759','199905','9','202904','16974','25','1','P','90','10','115000','90','7','R','N','FRM','IL','SF','60100','F199Q1000247','N','360','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('678','199904','9','202903','45300','000','1','P','80','25','112000','80','6.875','R','N','FRM','FL','SF','33700','F199Q1000248','C','360','01','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('744','199903','N','202902','29620','000','1','P','80','25','120000','80','7.375','T','N','FRM','MI','SF','48900','F199Q1000249','N','360','02','Other sellers','BANKOFAMERICA,NA','
','');
INSERT INTO raw_freddie_origination VALUES ('771','199903','Y','202902','','999','1','P','80','25','60000','80','7.375','R','','FRM','OH','SF','43500','F199Q1000250','P','360','01','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('659','199905','N','202904','24340','000','1','P','80','55','95000','80','7.25','R','N','FRM','MI','SF','49300','F199Q1000251','C','360','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('729','199905','N','202904','27260','000','1','P','80','39','117000','80','7.375','T','N','FRM','FL','SF','32200','F199Q1000252','P','360','02','Other sellers','GMACMTGECORP','
','');
INSERT INTO raw_freddie_origination VALUES ('762','199903','N','202902','24580','000','1','P','80','27','109000','80','7.25','T','N','FRM','WI','SF','54100','F199Q1000253','N','360','02','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('754','199903','N','202902','36420','000','1','P','73','30','60000','73','6.75','T','N','FRM','OK','SF','73100','F199Q1000254','P','360','01','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('741','199903','N','202902','47644','000','1','P','73','40','128000','73','6.875','R','N','FRM','MI','SF','48800','F199Q1000255','N','360','02','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('735','199903','N','202902','16974','12','1','P','80','25','115000','80','6.75','R','N','FRM','IL','SF','60000','F199Q1000256','C','360','01','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('735','199904','N','202903','18880','000','1','P','62','43','110000','62','6.75','T','N','FRM','FL','SF','32500','F199Q1000257','N','360','01','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('714','199903','N','202902','47894','000','1','P','80','34','160000','80','6.75','T','N','FRM','VA','SF','20100','F199Q1000258','N','360','02','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('745','199904','Y','202903','47644','30','1','P','95','38','94000','95','6.5','R','N','FRM','MI','CO','48300','F199Q1000259','P','360','01','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('757','199904','N','202903','40980','000','1','P','52','18','58000','52','6.875','R','N','FRM','MI','SF','48600','F199Q1000260','C','360','01','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('726','199904','N','202903','41884','17','1','P','80','50','184000','80','6.375','T','N','FRM','CA','SF','94900','F199Q1000261','C','360','01','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('783','199905','N','202904','11540','000','1','P','64','20','140000','64','6.75','T','N','FRM','WI','SF','54100','F199Q1000262','C','360','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('743','199904','9','202903','41100','000','1','P','56','11','112000','56','6.75','R','N','FRM','UT','SF','84700','F199Q1000263','N','360','02','Other sellers','GMACMTGECORP','
','');
INSERT INTO raw_freddie_origination VALUES ('657','199905','N','202904','27500','999','1','P','74','19','65000','74','7.2','R','N','FRM','WI','SF','53500','F199Q1000264','C','360','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('731','199904','N','202903','45780','25','1','P','90','25','194000','90','6.875','T','N','FRM','OH','SF','43600','F199Q1000265','P','360','02','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('749','199905','N','202904','11460','000','1','P','40','23','125000','40','7','R','N','FRM','MI','SF','48100','F199Q1000266','N','360','02','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('625','199905','N','202904','35660','000','1','P','75','40','174000','75','7','R','N','FRM','MI','SF','49000','F199Q1000267','C','360','02','STANDARD FEDERAL BAN','ABNAMROMTGEGROUP,INC','
','');
INSERT INTO raw_freddie_origination VALUES ('775','199905','N','202904','33340','000','1','P','80','18','69000','80','7.125','T','N','FRM','WI','SF','53000','F199Q1000268','N','360','02','Other sellers','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('657','199905','Y','202904','42044','12','1','P','85','48','224000','85','7.375','T','N','FRM','CA','SF','92800','F199Q1000269','P','360','01','BISHOP'S GATE RESIDE','Other servicers','
','');
Traceback (most recent call last):
  File "2_populate_raw_tables.py", line 40, in <module>
    populate("raw_freddie_origination", 27)
  File "2_populate_raw_tables.py", line 22, in populate
    c.execute(sql_str)
sqlite3.OperationalError: near "S": syntax error

```

**Comment by JamesPaulKnox** [comment]
I believe `'BISHOP'S GATE RESIDE'` is what is causing the error.

If I clean the input by deleting instances of " ' " before passing it to make a SQL command, it should fix the error.

**Comment by JamesPaulKnox** [comment]
A simpler solution may be to simply use single quotes instead of double quotes, but that would mean that my usage of quotes throughout the program would not be consistent. Not only would that be considered by many to be bad practice, but it would confuse the heck out of me if I ever have to come back to it.

I'll be using this stackoverflow question as my proposed solution. https://stackoverflow.com/questions/3939361/remove-specific-characters-from-a-string-in-python

**Comment by JamesPaulKnox** [comment]
Previous commit has been tested to fix this issue. Here are some log outputs that contain Bishop's Gate to evidence the added code has removed instances of single quotes.

```
INSERT INTO raw_freddie_origination VALUES ('795','199903','Y','202902','24580','30','1','P','95','22','144000','95','6.75','B','N','FRM','WI','SF','54100','F199Q1187327','P','360','02','BISHOPS GATE RESIDE','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('780','199902','N','202901','36084','000','1','P','60','23','240000','60','6.75','B','N','FRM','CA','SF','94500','F199Q1187328','N','360','02','BISHOPS GATE RESIDE','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('748','199902','N','202901','','000','1','P','62','13','97000','62','6.75','B','N','FRM','LA','SF','70400','F199Q1187329','N','360','02','BISHOPS GATE RESIDE','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('737','199902','N','202901','29404','000','1','P','80','32','181000','80','6.75','B','N','FRM','IL','SF','60000','F199Q1187330','P','360','02','BISHOPS GATE RESIDE','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('785','199903','N','202902','12580','000','1','P','54','18','170000','54','6.75','R','N','FRM','MD','SF','21000','F199Q1187331','P','360','02','BISHOPS GATE RESIDE','WASHINGTONMUTUALBANK','
','');
INSERT INTO raw_freddie_origination VALUES ('694','199903','N','202902','','25','1','P','89','47','67000','89','6.75','R','N','FRM','MN','SF','56300','F199Q1187332','N','360','01','BISHOPS GATE RESIDE','Other servicers','
','');
INSERT INTO raw_freddie_origination VALUES ('637','199903','N','202902','','25','1','P','90','31','75000','90','6.75','T','N','FRM','MN','SF','56000','F199Q1187333','P','360','01','BISHOPS GATE RESIDE','Other servicers','
```
